name: character_ai_clone
description: A Character.ai clone app
publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  record: ^4.4.4
  audioplayers: ^5.2.1
  path_provider: ^2.1.2
  flutter_markdown: ^0.6.20
  # Isar Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path: ^1.8.3
  # CSV parsing
  csv: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Isar Generator
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8
  # Test dependencies
  plugin_platform_interface: ^2.1.8
  path_provider_platform_interface: ^2.1.2
  mockito: ^5.4.4
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/avatar.png
    - assets/data/Objetivos.csv
    - assets/data/habitos.csv
    - assets/data/Trilhas.csv
    - assets/data/habit-assistant-prompt-v13.json
    - assets/config/
    - assets/config/oracle/
    - assets/prompts/