import 'dart:typed_data';
import 'package:flutter/material.dart';
import '../models/journal_entry_model.dart';

/// Card widget for displaying a journal entry
class JournalEntryCard extends StatelessWidget {
  final JournalEntryModel entry;
  final String language;

  const JournalEntryCard({
    super.key,
    required this.entry,
    required this.language,
  });

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 2,
      margin: const EdgeInsets.symmetric(vertical: 8.0),
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header with metadata
            _buildHeader(),

            const SizedBox(height: 16),

            // Generated image (if available)
            if (entry.imageData != null) ...[
              _buildGeneratedImage(),
              const SizedBox(height: 16),
            ],

            // Journal content
            _buildContent(),

            const SizedBox(height: 12),

            // Footer with generation info
            _buildFooter(),
          ],
        ),
      ),
    );
  }

  /// Build the header with date and language info
  Widget _buildHeader() {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(
          entry.getTimeAgo(language),
          style: TextStyle(
            fontSize: 12,
            color: Colors.grey[500],
          ),
        ),
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
          decoration: BoxDecoration(
            color: Colors.blue[50],
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: Colors.blue[200]!),
          ),
          child: Text(
            language == 'pt_BR' ? 'PT' : 'EN',
            style: TextStyle(
              fontSize: 12,
              color: Colors.blue[700],
              fontWeight: FontWeight.w500,
            ),
          ),
        ),
      ],
    );
  }

  /// Build the generated image display
  Widget _buildGeneratedImage() {
    if (entry.imageData == null) return const SizedBox.shrink();

    final imageBytes = Uint8List.fromList(entry.imageData!);

    return Container(
      width: double.infinity,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(12),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.1),
            blurRadius: 8,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(12),
        child: GestureDetector(
          onTap: () => _showFullScreenImage(imageBytes),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Image
              Image.memory(
                imageBytes,
                width: double.infinity,
                height: 200,
                fit: BoxFit.cover,
              ),
            ],
          ),
        ),
      ),
    );
  }

  /// Show full-screen image viewer
  void _showFullScreenImage(Uint8List imageBytes) {
    // Note: This would need to be called with context from parent widget
    // For now, we'll keep the tap gesture but implement full-screen later
  }

  /// Build the main journal content
  Widget _buildContent() {
    return SelectableText(
      entry.content,
      style: const TextStyle(
        fontSize: 16,
        height: 1.5,
        color: Colors.black87,
      ),
    );
  }

  /// Build the footer with generation metadata
  Widget _buildFooter() {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: Colors.grey[50],
        borderRadius: BorderRadius.circular(8),
      ),
      child: Row(
        children: [
          Icon(
            Icons.auto_awesome,
            size: 16,
            color: Colors.grey[600],
          ),
          const SizedBox(width: 8),
          Expanded(
            child: Text(
              language == 'pt_BR'
                  ? 'Gerado por I-There • ${entry.messageCount} mensagens, ${entry.activityCount} atividades • ${entry.generationTimeSeconds.toStringAsFixed(1)}s'
                  : 'Generated by I-There • ${entry.messageCount} messages, ${entry.activityCount} activities • ${entry.generationTimeSeconds.toStringAsFixed(1)}s',
              style: TextStyle(
                fontSize: 12,
                color: Colors.grey[600],
              ),
            ),
          ),
        ],
      ),
    );
  }
}
